Progress bar added
LTKills/heroes-build-scrapper pull request #42
Opened 2018-10-23 21:58 UTC by allangoncalves

Added a progress bar so the user can see the percentage of the build update and the time spent while doing it.

2018-10-25 12:52 UTC, LTKills commented
Thank you for comtributing, but unfortunately I cannot accept this PR. Every PR should tackle an specific issue and the contributos should be assigned to the issue for the PR to be accepted. Please open an issue about It and read the contributing section on README

2018-10-26 00:16 UTC, gmelodie requested changes
Looks good, be sure to add your github nick on `PLAYERS.md` as well

2018-10-26 00:16 UTC, LTKills commented on src/heroes_build_scrapper/data.py
> +    print('Updating Heroes')
:bike: (bike means optional)
I prefer the original phrasing of this

2018-10-26 00:16 UTC, LTKills commented on src/heroes_build_scrapper/data.py
> +
:scissors:

2018-10-26 14:35 UTC, allangoncalves commented
The old updating message is back! :)

2018-10-27 00:53 UTC, LTKills commented
I commented the :scissors:, please recheck that

2021-09-13 12:38 UTC, closed without merging